version: "3.6"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORKSPACE=/workspaces/capella_orb_slam3_dev
      target: dev
    volumes:
      - ../:/workspaces/capella_ros_docker
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/udev:/etc/udev
      - /run/udev/control:/run/udev/control  
    devices:
      - /dev/dri:/dev/dri
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - DISPLAY=:0
    network_mode: bridge
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: sleep infinity
    user: ros
    